[2024-09-11 15:55:04,297][flwr][INFO] - Starting Flower simulation, config: ServerConfig(num_rounds=10, round_timeout=None)
[2024-09-11 15:55:13,271][flwr][INFO] - Flower VCE: Ray initialized with resources: {'memory': 598730343.0, 'node:__internal_head__': 1.0, 'node:127.0.0.1': 1.0, 'CPU': 8.0, 'object_store_memory': 299365171.0}
[2024-09-11 15:55:13,272][flwr][INFO] - Initializing global parameters
[2024-09-11 15:55:13,272][flwr][INFO] - Requesting initial parameters from one random client
[2024-09-11 15:55:17,155][flwr][ERROR] - [36mray::launch_and_get_parameters()[39m (pid=8944, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1843, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1877, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 978, in ray._raylet.raise_if_dependency_failed
ray.exceptions.RaySystemError: System error: No module named 'client'
traceback: Traceback (most recent call last):
  File "c:\Users\PC\anaconda3\envs\flower\Lib\site-packages\ray\_private\serialization.py", line 423, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\PC\anaconda3\envs\flower\Lib\site-packages\ray\_private\serialization.py", line 280, in _deserialize_object
    return self._deserialize_msgpack_data(data, metadata_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\PC\anaconda3\envs\flower\Lib\site-packages\ray\_private\serialization.py", line 235, in _deserialize_msgpack_data
    python_objects = self._deserialize_pickle5_data(pickle5_data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\PC\anaconda3\envs\flower\Lib\site-packages\ray\_private\serialization.py", line 223, in _deserialize_pickle5_data
    obj = pickle.loads(in_band, buffers=buffers)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'client'
