[2024-09-25 11:30:25,998][flwr][WARNING] - Both server and strategy were provided, ignoring strategy
[2024-09-25 11:30:26,000][flwr][INFO] - Starting Flower simulation, config: ServerConfig(num_rounds=50, round_timeout=None)
[2024-09-25 11:30:34,454][flwr][INFO] - Flower VCE: Ray initialized with resources: {'CPU': 12.0, 'object_store_memory': 539802009.0, 'memory': 1079604020.0, 'node:127.0.0.1': 1.0, 'node:__internal_head__': 1.0}
[2024-09-25 11:30:34,454][flwr][INFO] - Initializing global parameters
[2024-09-25 11:30:34,454][flwr][INFO] - Requesting initial parameters from one random client
[2024-09-25 11:30:38,287][flwr][ERROR] - [36mray::launch_and_get_parameters()[39m (pid=12500, ip=127.0.0.1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BinaryNet.__init__() got an unexpected keyword argument 'input_dim'

The above exception was the direct cause of the following exception:

[36mray::launch_and_get_parameters()[39m (pid=12500, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1890, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1991, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 135, in launch_and_get_parameters
    client: Client = _create_client(client_fn, cid)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
                              ^^^^^^^^^^^^^^
  File "c:\Users\andri\OneDrive\Desktop\Tesi Palumbo\Tesi-Francesco\client_fedavg.py", line 112, in client_fn
    net = instantiate(model).to(device)
          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andri\anaconda3\envs\flower\Lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'model.BinaryNet':
TypeError("BinaryNet.__init__() got an unexpected keyword argument 'input_dim'")
full_key: model
