[2024-09-12 12:15:10,853][flwr][INFO] - Starting Flower simulation, config: ServerConfig(num_rounds=10, round_timeout=None)
[2024-09-12 12:15:26,004][flwr][INFO] - Flower VCE: Ray initialized with resources: {'node:127.0.0.1': 1.0, 'object_store_memory': 845763379.0, 'CPU': 8.0, 'memory': 1691526759.0, 'node:__internal_head__': 1.0}
[2024-09-12 12:15:26,006][flwr][INFO] - Initializing global parameters
[2024-09-12 12:15:26,007][flwr][INFO] - Requesting initial parameters from one random client
[2024-09-12 12:15:32,584][flwr][INFO] - Received initial parameters from one random client
[2024-09-12 12:15:32,585][flwr][INFO] - Evaluating initial parameters
[2024-09-12 12:15:32,638][flwr][INFO] - initial parameters (loss, other metrics): 43.98814926147461, {'accuracy': 0.5616666666666666}
[2024-09-12 12:15:32,640][flwr][INFO] - FL starting
[2024-09-12 12:15:32,641][flwr][DEBUG] - fit_round 1: strategy sampled 2 clients (out of 2)
[2024-09-12 12:15:32,679][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=15320, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\Desktop\PoliMi\Magistrale\Tesi\Progetto\Tesi-Francesco\client.py", line 37, in fit
    lr = config["lr"]
         ~~~~~~^^^^^^
KeyError: 'lr'
[2024-09-12 12:15:39,487][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=12260, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\Desktop\PoliMi\Magistrale\Tesi\Progetto\Tesi-Francesco\client.py", line 37, in fit
    lr = config["lr"]
         ~~~~~~^^^^^^
KeyError: 'lr'
[2024-09-12 12:15:39,493][flwr][DEBUG] - fit_round 1 received 0 results and 2 failures
[2024-09-12 12:15:39,541][flwr][INFO] - fit progress: (1, 43.98814926147461, {'accuracy': 0.5616666666666666}, 6.90089689999877)
[2024-09-12 12:15:39,543][flwr][DEBUG] - evaluate_round 1: strategy sampled 2 clients (out of 2)
