[2024-09-19 11:47:01,276][numexpr.utils][INFO] - NumExpr defaulting to 8 threads.
[2024-09-19 11:47:03,498][flwr][INFO] - Starting Flower simulation, config: ServerConfig(num_rounds=10, round_timeout=None)
[2024-09-19 11:47:11,559][flwr][INFO] - Flower VCE: Ray initialized with resources: {'node:__internal_head__': 1.0, 'CPU': 8.0, 'node:127.0.0.1': 1.0, 'memory': 853197620.0, 'object_store_memory': 426598809.0}
[2024-09-19 11:47:11,560][flwr][INFO] - Initializing global parameters
[2024-09-19 11:47:11,560][flwr][INFO] - Requesting initial parameters from one random client
[2024-09-19 11:47:14,651][flwr][INFO] - Received initial parameters from one random client
[2024-09-19 11:47:14,652][flwr][INFO] - Evaluating initial parameters
[2024-09-19 11:47:14,779][flwr][INFO] - initial parameters (loss, other metrics): 0.9455388108889262, {'global accuracy': 0.48444444444444446}
[2024-09-19 11:47:14,780][flwr][INFO] - FL starting
[2024-09-19 11:47:14,781][flwr][DEBUG] - fit_round 1: strategy sampled 2 clients (out of 2)
[2024-09-19 11:47:14,813][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=17800, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\PC\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "C:\Users\PC\anaconda3\envs\flower\Lib\site-packages\flwr\client\client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\anaconda3\envs\flower\Lib\site-packages\flwr\client\app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\VscodeProjects\Tesi-Francesco\clients\client_scaffold.py", line 47, in fit
    parameters = parameters[:, len(parameters)//2]
                 ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not tuple
[2024-09-19 11:47:18,328][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=11364, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\PC\anaconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "C:\Users\PC\anaconda3\envs\flower\Lib\site-packages\flwr\client\client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\anaconda3\envs\flower\Lib\site-packages\flwr\client\app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\VscodeProjects\Tesi-Francesco\clients\client_scaffold.py", line 47, in fit
    parameters = parameters[:, len(parameters)//2]
                 ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not tuple
[2024-09-19 11:47:18,337][flwr][DEBUG] - fit_round 1 received 0 results and 2 failures
[2024-09-19 11:47:18,383][flwr][INFO] - fit progress: (1, 0.9455388108889262, {'global accuracy': 0.48444444444444446}, 3.6019697000156157)
[2024-09-19 11:47:18,384][flwr][DEBUG] - evaluate_round 1: strategy sampled 2 clients (out of 2)
[2024-09-19 11:47:29,008][flwr][DEBUG] - evaluate_round 1 received 2 results and 0 failures
